### ISSUE TITLE
CFN deploy error : ZipFile length cannot exceed 4096 characters

### ISSUE THREAD

**Issue by jdebnath21** [Signiant/dynamodb-replication#4]
I keep getting this error, am I doing something wrong ?

ZipFile length cannot exceed 4096 characters. For larger source use S3Bucket/S3Key properties instead.

![image](https://user-images.githubusercontent.com/29192397/29494628-ee43eabc-85cb-11e7-9488-3f996e76fdbf.png)

**Comment by JSeed** [comment]
Strange... I was unable to reproduce the issue on a fresh stack.  
I have seen this before though, the character limit is the reason I uglify the code during the Grunt process.
Could you verify that all of the Grunt tasks are completing successfully (primarily 'uglify:dist')?

**Comment by JSeed** [comment]
I was unable to reproduce this with a fresh stack, seems like there might have been an issue building the template.  
To ease the deployment for yourself and future users, I have created a [v1.0.0](https://github.com/Signiant/dynamodb-replication/releases/tag/v1.0.0) release containing the pre-built cloudformation template.
Creating a new stack using the [template](https://github.com/Signiant/dynamodb-replication/releases/download/v1.0.0/replicator.cfn.json) attached to the release should resolve this issue.

**Comment by jdebnath21** [comment]
Thanks Jon.

Let me give that a spin and see what I get.

Many thanks for your help, really appreciate it.

Regards
Jay

*Regards*
*Jay*

**Comment by JSeed** [comment]
No worries,  let me know if you have any more issues

**Comment by JSeed** [comment]
@dnorth98 Assuming this issue can now be closed

**Comment by ranjit009** [comment]
How did you resolve this issue ? CFN deploy error : ZipFile length cannot exceed 4096 characters.
Thanks in Advance.
