### ISSUE TITLE
bidirectional replication

### ISSUE THREAD

**Issue by dly9014** [Signiant/dynamodb-replication#5]
Consider the use case of a common dataset that is available across multiple regions in an active-active architecture. Clients access the copy of the dataset local to their region to minimize latency. Can this solution be used to maintain consistency between tables in a bidirectional manner or will it initiate infinite replication loops?

**Comment by JSeed** [comment]
This solution only facilitates single master replication.  Multi master setups will result in replication loops, as you suggested.
If the data set is static (at least as far as the clients are concerned) you could replicate to multiple regions from one master, but if clients need to be able to modify the data in their local region this solution will not work.  

If you are willing to put in some work to adapt the solution to your needs, Under Armour gave an interesting presentation on multi-master replication at re:Invent 2016 ([vod](https://www.youtube.com/watch?v=NtaTC2Fq7Wo)).  Unfortunately, I don't think they have open sourced any of the code behind it.

**Comment by dly9014** [comment]
Hi Jon, thanks. I did see that preso in my research. I'm looking for a lightweight approach so will probably restructure my writes to only go to one region.
